### ISSUE TITLE
Toggle between {...} and [...] doesn't account for nested brackets.

### ISSUE THREAD

**Issue by sylbeth** [texstudio-org/texstudio-macro#16]
I was using the Toggle between macro, and I realised that, if you use brackets more than one time: e.g. forallin[v]{A_{2}} -> forallin[v][A_{2]}, it doesn't account for them. Maybe it could be helped with an loop here:

rightEnd = line.indexOf( rightChar, leftEnd);

rightEnd = leftEnd
leftPivot = leftEnd
do {
    leftPivot = line.indexOf(leftChar, leftPivot+1);
    rightEnd = line.indexOf(rightChar, rightEnd+1);
} while (leftPivot > -1 && leftPivot < rightEnd)

**Comment by sunderme** [comment]
@octaeder  I guess that is for you.

**Comment by octaeder** [comment]
@sunderme Please add label enhancement here and merge PR. Thx.
