### ISSUE TITLE
autoLabel.txsMacro doens't work anymore

### ISSUE THREAD

**Issue by desk7** [texstudio-org/texstudio-macro#28]
The issue is linked to https://github.com/texstudio-org/texstudio/issues/2728.
The new perl regex compatible engine (QRegularExpression) thinks that the trigger regex expression is faulty: "lookbehind assertion is not fixed length".

Furthermore, line 19
```
 "title = title.toLowerCase().match(/\w+/g).join(\"-\");",
```
should be
```
 "title = title.toLowerCase().match(/\\w+/g).join(\"-\");",
```
ie with `\\w`, not `\w`.

**Comment by sunderme** [comment]
pull request ?
