### ISSUE TITLE
format tex deletes parts of the document

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio-macro#3]
My tex sources is partially destroyed by the format tex macro. Test document and result is attached.

[document2.tex.txt](https://github.com/texstudio-org/texstudio-macro/files/4241538/document2.tex.txt)
[document2_result.tex.txt](https://github.com/texstudio-org/texstudio-macro/files/4241542/document2_result.tex.txt)

**Comment by MeanSquaredError** [comment]
OK, I see three issues here:
1. The text content after `\end{verbatim}` is deleted.
2. The content of the `verbatim` environment is altered.
3. `\usepackage{..}` should probably go on a separate line.

Now to fix them one by one ...
