### ISSUE TITLE
Texstudio not found Process exited normally

### ISSUE THREAD

**Issue by MohamedaliS** [texstudio-org/texstudio-macro#30]
Better bibtex add on is already installed in Zotero.

I imported the "zoteroPicker.txsMacro" in Texstudio macros.
zotero pops up. However, adding citation is not working. The message is 

Process started: curl -s http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true

TeXstudio not found
Process exited normally

I am using Ubuntu 22.04.3 LTS.

What I am missing?

**Comment by sunderme** [comment]
duplicate to https://github.com/texstudio-org/texstudio/issues/3337
